name: Godot CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v2.0.1
      with:
        godot_executable_download_url: 'https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_win64.exe'  # Use Windows version

    - name: Export Project
      run: |
        mkdir -p build
        godot --export "Windows Desktop" build/MyGame.exe  # Adjust for Windows

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Game Build
        path: build/

