name: Godot CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Godot
      uses: chickensoft-games/setup-godot@v2.0.1
      with:
        version: '4.3'

    - name: Export Project
      run: |
        mkdir -p build
        godot --export "Linux/X11" build/MyGame.x86_64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Game Build
        path: build/
